spring:
  h2:
    console:
      enable: true



  jpa:
    show_sql: true
    #hibernate:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
#
#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace