spring:
  h2:
    console:
      enable: true
#  datasource:
#    url: jdbc:mariadb://localhost:3306/mytest
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: root
#    password: root

  jpa:
    show_sql: true
    #hibernate:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
#
#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace